version: "3.7"
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: manifest-api
    image: manifest-api
    command: python manage.py runserver 0.0.0.0:$API_PORT
    volumes:
      - ${PWD}/api/:/usr/src/app/
    environment:
      - SQL_ENGINE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
      - DEBUG
      - DJANGO_ALLOWED_HOSTS
      - API_PORT
    depends_on:
        postgres:
          condition: service_healthy
    ports:
      - $API_PORT:$API_PORT

  postgres:
    image: postgres:13.3-alpine
    container_name: manifest-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ${PWD}/db/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 20s
      retries: 10

volumes:
  postgres_data:
